#ifndef DECORATEDATA_H
#define DECORATEDATA_H

#include <string>
#include <vector>

struct flagChange
{
    uint32_t flag;
    std::string added;
    std::string removed;
};

struct translationFlags
{
    uint32_t flag;
    int value;
};

//This contains the necessary arrays for writing DECORATE data
const std::vector<std::string> ZDOOMNAMES
{
    "OFFSET", //Exists to offset index to start at 1
	"DoomPlayer",
	"ZombieMan",
	"ShotgunGuy",
	"Archvile",
	"ArchvileFire",
	"Revenant",
	"RevenantTracer",
	"RevenantTracerSmoke",
	"Fatso",
	"FatShot",
	"ChaingunGuy",
	"DoomImp",
	"Demon",
	"Spectre",
	"Cacodemon",
	"BaronOfHell",
	"BaronBall",
	"HellKnight",
	"LostSoul",
	"SpiderMastermind",
	"Arachnotron",
	"Cyberdemon",
	"PainElemental",
	"WolfensteinSS",
	"CommanderKeen",
	"BossBrain",
	"BossEye",
	"BossTarget",
	"SpawnShot",
	"SpawnFire",
	"ExplosiveBarrel",
	"DoomImpBall",
	"CacodemonBall",
	"Rocket",
	"PlasmaBall",
	"BFGBall",
	"ArachnotronPlasma",
	"BulletPuff",
	"Blood",
	"TeleportFog",
	"ItemFog",
	"TeleportDest",
	"BFGExtra",
	"GreenArmor",
	"BlueArmor",
	"HealthBonus",
	"ArmorBonus",
	"BlueCard",
	"RedCard",
	"YellowCard",
	"YellowSkull",
	"RedSkull",
	"BlueSkull",
	"Stimpack",
	"Medikit",
	"Soulsphere",
	"InvulnerabilitySphere",
	"Berserk",
	"BlurSphere",
	"RadSuit",
	"Allmap",
	"Infrared",
	"Megasphere",
	"Clip",
	"ClipBox",
	"RocketAmmo",
	"RocketBox",
	"Cell",
	"CellPack",
	"Shell",
	"ShellBox",
	"Backpack",
	"BFG9000",
	"Chaingun",
	"Chainsaw",
	"RocketLauncher",
	"PlasmaRifle",
	"Shotgun",
	"SuperShotgun",
	"TechLamp",
	"TechLamp2",
	"Column",
	"TallGreenColumn",
	"ShortGreenColumn",
	"TallRedColumn",
	"ShortRedColumn",
	"SkullColumn",
	"HeartColumn",
	"EvilEye",
	"FloatingSkull",
	"TorchTree",
	"BlueTorch",
	"GreenTorch",
	"RedTorch",
	"ShortBlueTorch",
	"ShortGreenTorch",
	"ShortRedTorch",
	"Stalagtite",
	"TechPillar",
	"Candlestick",
	"Candelabra",
	"BloodyTwitch",
	"Meat2",
	"Meat3",
	"Meat4",
	"Meat5",
	"NonsolidMeat2",
	"NonsolidMeat4",
	"NonsolidMeat3",
	"NonsolidMeat5",
	"NonsolidTwitch",
	"DeadCacodemon",
	"DeadMarine",
	"DeadZombieMan",
	"DeadDemon",
	"DeadLostSoul",
	"DeadDoomImp",
	"DeadShotgunGuy",
	"GibbedMarine",
	"GibbedMarineExtra",
	"HeadsOnAStick",
	"Gibs",
	"HeadOnAStick",
	"HeadCandles",
	"DeadStick",
	"LiveStick",
	"BigTree",
	"BurningBarrel",
	"HangNoGuts",
	"HangBNoBrain",
	"HangTLookingDown",
	"HangTSkull",
	"HangTLookingUp",
	"HangTNoBrain",
	"ColonGibs",
	"SmallBloodPool",
	"BrainStem",
// Boom additional actors:
	"PointPusher",
	"PointPuller",
// MBF additional actors:
	"MBFHelperDog",
	"PlasmaBall1",
	"PlasmaBall2",
	"EvilSceptre",
	"UnholyBible",
// Actors added since Fist/Pistol can be changed despite not being things
    "Fist",
    "Pistol",
};

const std::vector<flagChange> ZDOOMFLAGS
{
	{0x00000001,	"+SPECIAL",			"-SPECIAL"},
	{0x00000002,	"+SOLID",			"-SOLID"},
	{0x00000004,	"+SHOOTABLE",		"-SHOOTABLE"},
	{0x00000008,	"+NOSECTOR",		"-NOSECTOR"},
	{0x00000010,	"+NOBLOCKMAP",		"-NOBLOCKMAP"},
	{0x00000020,	"+AMBUSH",			"-AMBUSH"},
	{0x00000040,	"+JUSTHIT",			"-JUSTHIT"},
	{0x00000080,	"+JUSTATTACKED",	"-JUSTATTACKED"},
	{0x00000100,	"+SPAWNCEILING",	"-SPAWNCEILING"},
	{0x00000200,	"+NOGRAVITY",		"-NOGRAVITY"},
	{0x00000400,	"+DROPOFF",			"-DROPOFF"},
	{0x00000800,	"+PICKUP",			"-PICKUP"},
	{0x00001000,	"+NOCLIP",			"-NOCLIP"},
//	{0x00002000,	"+SLIDE",			"-SLIDE"},
	{0x00004000,	"+FLOAT",			"-FLOAT"},
	{0x00008000,	"+TELEPORT",		"-TELEPORT"},
	{0x00010000,	"+MISSILE",			"-MISSILE"},
	{0x00020000,	"+DROPPED",			"-DROPPED"},
	{0x00040000,	"+SHADOW",			"-SHADOW"},
	{0x00080000,	"+NOBLOOD",			"-NOBLOOD"},
	{0x00100000,	"+CORPSE",			"-CORPSE"},
//	{0x00200000,	"+INFLOAT",			"-INFLOAT"},
	{0x00400000,	"+COUNTKILL",		"-COUNTKILL"},
	{0x00800000,	"+COUNTITEM",		"-COUNTITEM"},
	{0x01000000,	"+SKULLFLY",		"-SKULLFLY"},
	{0x02000000,	"+NOTDMATCH",		"-NOTDMATCH"},
//	{0x04000000,	"+TRANSLATION1",	"-TRANSLATION1"},
//	{0x08000000,	"+TRANSLATION2",	"-TRANSLATION2"},
	{0x10000000,	"+TOUCHY",			"-TOUCHY"},
//	{0x20000000,	"+BOUNCES",			"-BOUNCES"},
	{0x40000000,	"+FRIEND",			"-FRIEND"},
//	{0x80000000,	"+TRANSLUCENT",		"-TRANSLUCENT"},

	{0x20000000,	"+BOUNCEONWALLS\n\t+BOUNCEONFLOORS\n\t+BOUNCEONCEILINGS",	"-BOUNCEONWALLS\n\t-BOUNCEONFLOORS\n\t-BOUNCEONCEILINGS"},
    {0x80000000,	"RenderStyle \"Translucent\"\n\tAlpha 0.5",	"RenderStyle \"Normal\""},
};

const std::vector<translationFlags> ZDOOMTRANSLATION
{
	{0x00000000,	0},
	{0x04000000,	1},
	{0x08000000,	2},
};

//Name of the thing properties
const std::vector<std::string> ZDOOMTHINGPROPERTIES
{
    "ID",
    "Health",
    "Speed",
    "Radius",
    "Height",
    "Damage",
    "ReactionTime",
    "PainChance",
    "Mass",
};

//Name of the thing sound types
const std::vector<std::string> ZDOOMTHINGSOUNDS
{
    "SeeSound",
    "AttackSound",
    "PainSound",
    "DeathSound",
    "ActiveSound",
};

//Name of the sounds in ZDoom
const std::vector<std::string> ZDOOMSOUNDNAMES
{
    "",
	"weapons/pistol",
	"weapons/shotgf",
	"weapons/shotgr",
	"weapons/sshotf",
	"weapons/sshoto",
	"weapons/sshotc",
	"weapons/sshotl",
	"weapons/plasmaf",
	"weapons/bfgf",
	"weapons/sawup",
	"weapons/sawidle",
	"weapons/sawfull",
	"weapons/sawhit",
	"weapons/rocklf",
	"weapons/bfgx",
	"imp/attack",
	"imp/shotx",
	"plats/pt1_strt",
	"plats/pt1_stop",
	"doors/dr1_open",
	"doors/dr1_clos",
	"plats/pt1_mid",
	"switches/normbutn",
	"switches/exitbutn",
	"*pain100",
	"demon/pain",
	"grunt/pain",
	"vile/pain",
	"fatso/pain",
	"pain/pain",
	"misc/gibbed",
	"misc/i_pkup",
	"misc/w_pkup",
	"*land",
	"misc/teleport",
	"grunt/sight",
	"grunt/sight",
	"grunt/sight",
	"imp/sight",
	"imp/sight",
	"demon/sight",
	"caco/sight",
	"baron/sight",
	"cyber/sight",
	"spider/sight",
	"baby/sight",
	"knight/sight",
	"vile/sight",
	"fatso/sight",
	"pain/sight",
	"skull/melee",
	"demon/melee",
	"skeleton/melee",
	"vile/start",
	"imp/melee",
	"skeleton/swing",
	"*death",
	"*xdeath",
	"grunt/death",
	"grunt/death",
	"grunt/death",
	"imp/death",
	"imp/death",
	"demon/death",
	"caco/death",
	"misc/unused",
	"baron/death",
	"cyber/death",
	"spider/death",
	"baby/death",
	"vile/death",
	"knight/death",
	"pain/death",
	"skeleton/death",
	"grunt/active",
	"imp/active",
	"demon/active",
	"baby/active",
	"baby/walk",
	"vile/active",
	"*grunt",
	"world/barrelx",
	"*fist",
	"cyber/hoof",
	"spider/walk",
	"weapons/chngun",
	"misc/chat2",
	"doors/dr2_open",
	"doors/dr2_clos",
	"misc/spawn",
	"vile/firecrkl",
	"vile/firestrt",
	"misc/p_pkup",
	"brain/spit",
	"brain/cube",
	"brain/sight",
	"brain/pain",
	"brain/death",
	"fatso/attack",
	"fatso/death",
	"wolfss/sight",
	"wolfss/death",
	"keen/pain",
	"keen/death",
	"skeleton/active",
	"skeleton/sight",
	"skeleton/attack",
	"misc/chat",
	"dog/sight",
	"dog/attack",
	"dog/active",
	"dog/death",
	"dog/pain",
};

//Name of ammo types
const std::vector<std::string> ZDOOMAMMONAMES
{
    "Clip",
    "Shell",
    "Cell",
    "RocketAmmo",
    "", //Infinite
};

//Name of standard thing states
const std::vector<std::string> ZDOOMTHINGSTATES
{
    "Spawn",
    "See",
    "Pain",
    "Melee",
    "Missile",
    "Death",
    "XDeath",
    "Raise",
    "Deselect",
    "Select",
    "Ready",
    "Fire",
    "Flash",
};

//Name of sprites in ZDoom
const std::vector<std::string> ZDOOMSPRITENAMES
{
	"TROO","SHTG","PUNG","PISG","PISF","SHTF","SHT2","CHGG","CHGF","MISG",
	"MISF","SAWG","PLSG","PLSF","BFGG","BFGF","BLUD","PUFF","BAL1","BAL2",
	"PLSS","PLSE","MISL","BFS1","BFE1","BFE2","TFOG","IFOG","PLAY","POSS",
	"SPOS","VILE","FIRE","FATB","FBXP","SKEL","MANF","FATT","CPOS","SARG",
	"HEAD","BAL7","BOSS","BOS2","SKUL","SPID","BSPI","APLS","APBX","CYBR",
	"PAIN","SSWV","KEEN","BBRN","BOSF","ARM1","ARM2","BAR1","BEXP","FCAN",
	"BON1","BON2","BKEY","RKEY","YKEY","BSKU","RSKU","YSKU","STIM","MEDI",
	"SOUL","PINV","PSTR","PINS","MEGA","SUIT","PMAP","PVIS","CLIP","AMMO",
	"ROCK","BROK","CELL","CELP","SHEL","SBOX","BPAK","BFUG","MGUN","CSAW",
	"LAUN","PLAS","SHOT","SGN2","COLU","SMT2","GOR1","POL2","POL5","POL4",
	"POL3","POL1","POL6","GOR2","GOR3","GOR4","GOR5","SMIT","COL1","COL2",
	"COL3","COL4","CAND","CBRA","COL6","TRE1","TRE2","ELEC","CEYE","FSKU",
	"COL5","TBLU","TGRN","TRED","SMBT","SMGT","SMRT","HDB1","HDB2","HDB3",
	"HDB4","HDB5","HDB6","POB1","POB2","BRS1","TLMP","TLP2",
	"TNT1","DOGS","PLS1","PLS2","BON3","BON4"	// Added by MBF
};

//Name of sprite subnumbers in ZDoom
const std::vector<char> ZDOOMSPRITESUBNAMES
{
    'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','\\',']'
};

#endif //DECORATEDATA_H
