CLASS AliensTCLightweightDrone : ZombieMan { 
	Default {
		
		Health 180;
		Speed 10;
		Radius 16;
		Damage 30;
		PainChance 180;
		Mass 20;
		SeeSound "imp/sight";
		AttackSound "";
		DeathSound "imp/death";
		ActiveSound "imp/active";
		Obituary "%o was killed by an Alien Drone"
		Tag "Alien Drone"
	}
	States
	{
		Spawn:
			TROO AB 10 A_Look();
			Loop;
		See:
			TROO AABBCCDD 3 A_Chase();
			Loop;
		Pain:
			TROO H 2();
			TROO H 2 A_Pain();
			TROO AABBCCDD 3 A_Chase();
			goto See;
		Melee:
			TROO EF 8 A_FaceTarget();
			TROO G 6 A_TroopAttack();
			TROO AABBCCDD 3 A_Chase();
			goto See;
		Missile:
			TROO A -1();
			stop;
		Death:
			TROO I 8();
			TROO J 8 A_Scream();
			TROO K 6();
			TROO L 6 A_Fall();
			TROO M -1();
			stop;
		XDeath:
			TROO N 5();
			TROO O 5 A_XScream();
			BEXP D 5 A_Explode();
			TROO Q 5 A_Fall();
			TROO RST 5();
			TROO U -1();
			stop;
	}
}

CLASS AliensTCSilentExplodingWarrior : ShotgunGuy { 
	Default {
		
		Health 130;
		Speed 10;
		Radius 30;
		PainChance 180;
		Mass 400;
		SeeSound "";
		PainSound "";
		DeathSound "";
		ActiveSound "";
	}
	States
	{
		Spawn:
			SARG AA 10 A_Look();
			goto Spawn;
		See:
			SARG AABBCCDD 2 A_Chase();
			goto See;
		Pain:
			SARG H 2();
			SARG H 2 A_Pain();
			SARG AABBCCDD 2 A_Chase();
			goto See;
		Melee:
			SARG EF 8 A_FaceTarget();
			SARG G 8 A_SargAttack();
			SARG AABBCCDD 2 A_Chase();
			goto See;
		Missile:
			TROO A -1();
			stop;
		Death:
			TROO N 5();
			TROO O 5 A_XScream();
			BEXP D 5 A_Explode();
			TROO Q 5 A_Fall();
			TROO RST 5();
			TROO U -1();
			stop;
		XDeath:
			TROO A -1();
			stop;
	}
}

CLASS DH_DoomImp : DoomImp replaces DoomImp 3001 { 
	Default {
		
		Damage 30;
		DeathSound "demon/death";
	}
	States
	{
		XDeath:
			TROO N 5();
			TROO O 5 A_XScream();
			BEXP D 5 A_Explode();
			TROO Q 5 A_Fall();
			TROO RST 5();
			TROO UA -1();
			stop;
	}
}

CLASS DH_Demon : Demon replaces Demon 3002 { 
	Default {
		
		DeathSound "baron/death";
	}
	States
	{
		Spawn:
			SARG AA 10 A_Look();
			goto Spawn;
	}
}

CLASS DH_Spectre : Spectre replaces Spectre 58 { 
	Default {
		
		Health 130;
		-SHADOW;
	}
	States
	{
		Spawn:
			SARG AA 10 A_Look();
			goto Spawn;
		Death:
			TROO N 5();
			TROO O 5 A_XScream();
			BEXP D 5 A_Explode();
			TROO Q 5 A_Fall();
			TROO RST 5();
			TROO U -1();
			stop;
	}
}

CLASS DH_Cacodemon : Cacodemon replaces Cacodemon 3005 { 
	Default {
		
		Health 60;
		Speed 1;
		Radius 16;
		Height 36;
		PainChance 0;
		Mass 60;
		-SOLID;
		-NOGRAVITY;
		-FLOAT;
		-COUNTKILL;
		SeeSound "";
		PainSound "";
	}
	States
	{
		See:
			HEAD E 7();
			HEAD E 7 A_Pain();
			SPID J 7 A_Scream();
			SPID K 7 A_Fall();
			SPID L 7();
			SPID M 60();
			SPID NOPQ 7();
			HEAD BC 6 A_FaceTarget();
			HEAD D 0 Bright A_HeadAttack();
			COL2 A -1();
			stop;
		Pain:
			TROO A -1();
			stop;
		Missile:
			HEAD E 7();
			HEAD E 7 A_Pain();
			SPID J 7 A_Scream();
			SPID K 7 A_Fall();
			SPID L 7();
			SPID M 60();
			SPID NOPQ 7();
			HEAD BC 6 A_FaceTarget();
			HEAD D 0 Bright A_HeadAttack();
			COL2 A -1();
			stop;
		Death:
			ALEG B 5();
			ALEG C 5 A_XScream();
			ALEG D 5 A_Fall();
			ALEG E -1();
			stop;
	}
}

CLASS DH_BaronOfHell : BaronOfHell replaces BaronOfHell 3003 { 
	Default {
		
		Health 1500;
		Height 104;
		PainChance 100;
		Mass 1500;
	}
	States
	{
		See:
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Pain:
			POSS C 2();
			POSS C 2 A_Pain();
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Melee:
			POSS A 8 A_FaceTarget();
			BOSS A 8 A_FaceTarget();
			POSS B 8 A_BruisAttack();
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Missile:
			POSS A 8 A_FaceTarget();
			BOSS A 8 A_FaceTarget();
			POSS B 8 A_BruisAttack();
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Death:
			BOSS I 16();
			BOSS K 8();
			BOSS L 8 A_Fall();
			BOSS M 8();
			BOSS N 12();
			BOSS O -1 A_BossDeath();
			stop;
		Raise:
			BOSS ONMLKJI 8();
			BOSS AABBAADD 3 A_Chase();
			goto See;
	}
}

CLASS DH_BaronBall : BaronBall replaces BaronBall -1 { 
	Default {
		
		SeeSound "";
	}
	States
	{
		Spawn:
			BAL7 AB 4();
			goto Spawn;
		Death:
			BAL7 CDE 6();
			stop;
	}
}

CLASS DH_LostSoul : LostSoul replaces LostSoul 3006 { 
	Default {
		
		Health 50;
		Speed 10;
		Height 30;
		-NOGRAVITY;
		-FLOAT;
		+COUNTKILL;
		DeathSound "misc/gibbed";
	}
	States
	{
		Spawn:
			SPOS AB 10 A_Look();
			goto Spawn;
		See:
			SPOS AB 6 A_Chase();
			goto See;
		Pain:
			SPOS E 3();
			SPOS B 3 A_Pain();
			SPOS AB 6 A_Chase();
			goto See;
		Missile:
			SPOS C 10 A_FaceTarget();
			SPOS D 4 A_SkullAttack();
		State_591:
			SPOS CD 4();
			goto State_591;
		Death:
			SKUL F 5();
			SKUL G 5 A_Scream();
			SKUL H 5();
			SKUL I 5 A_Fall();
			SKUL JK 5();
			POSS T 5();
			POSS U -1();
			stop;
	}
}

CLASS DH_SpiderMastermind : SpiderMastermind replaces SpiderMastermind 7 { 
	Default {
		
		Health 1500;
		Radius 32;
		Height 104;
		PainChance 150;
		Mass 1500;
		SeeSound "baron/sight";
		AttackSound "";
		DeathSound "baron/death";
	}
	States
	{
		Spawn:
			BOSS AB 10 A_Look();
			goto Spawn;
		See:
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Pain:
			POSS C 2();
			POSS C 2 A_Pain();
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Melee:
			POSS A 8 A_FaceTarget();
			BOSS A 8 A_FaceTarget();
			POSS B 8 A_BruisAttack();
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Missile:
			TROO A -1();
			stop;
		Death:
			BOSS I 16();
			BOSS K 8();
			BOSS L 8 A_Fall();
			BOSS M 8();
			BOSS N 12();
			BOSS O -1 A_BossDeath();
			stop;
	}
}

CLASS DH_Cyberdemon : Cyberdemon replaces Cyberdemon 16 { 
	Default {
		
		Health 1500;
		Speed 12;
		Radius 32;
		Height 104;
		PainChance 150;
		Mass 1500;
		SeeSound "baron/sight";
		DeathSound "baron/death";
	}
	States
	{
		Spawn:
			BOSS AB 10 A_Look();
			goto Spawn;
		See:
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Pain:
			POSS C 2();
			POSS C 2 A_Pain();
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Melee:
			POSS A 8 A_FaceTarget();
			BOSS A 8 A_FaceTarget();
			POSS B 8 A_BruisAttack();
			BOSS AABBAADD 3 A_Chase();
			goto See;
		Missile:
			TROO A -1();
			stop;
		Death:
			BOSS I 16();
			BOSS K 8();
			BOSS L 8 A_Fall();
			BOSS M 8();
			BOSS N 12();
			BOSS O -1 A_BossDeath();
			stop;
	}
}

CLASS DH_ExplosiveBarrel : ExplosiveBarrel replaces ExplosiveBarrel 2035 { 
	Default {
		
		Speed 1;
	}
	States
	{
		Death:
			SPOS N 5 A_XScream();
			SPOS O 5 A_Fall();
			SPOS PQRST 5();
			SPOS U -1();
			stop;
	}
}

CLASS DH_DoomImpBall : DoomImpBall replaces DoomImpBall -1 { 
	Default {
		
	}
	States
	{
		Spawn:
			BAL7 AB 4();
			goto Spawn;
		Death:
			BAL7 CDE 6();
			stop;
	}
}

CLASS Facehugger : CacodemonBall replaces CacodemonBall -1 { 
	Default {
		
		Health 50;
		Radius 16;
		Height 25;
		Damage 3;
		PainChance 256;
		Mass 50;
		+SOLID;
		+SHOOTABLE;
		-NOBLOCKMAP;
		-NOGRAVITY;
		-DROPOFF;
		-MISSILE;
		+COUNTKILL;
		RenderStyle "Normal";
		SeeSound "";
		AttackSound "skull/melee";
		PainSound "demon/pain";
		DeathSound "misc/gibbed";
		ActiveSound "demon/active";
	}
	States
	{
		Spawn:
			SPOS AB 10 A_Look();
			goto Spawn;
		See:
			SPOS AB 6 A_Chase();
			goto See;
		Pain:
			SPOS E 3();
			SPOS B 3 A_Pain();
			SPOS AB 6 A_Chase();
			goto See;
		Missile:
			SPOS C 10 A_FaceTarget();
			SPOS D 4 A_SkullAttack();
		State_591:
			SPOS CD 4();
			goto State_591;
		Death:
			SKUL F 5();
			SKUL G 5 A_Scream();
			SKUL H 5();
			SKUL I 5 A_Fall();
			SKUL JK 5();
			POSS T 5();
			POSS U -1();
			stop;
	}
}

CLASS DH_Rocket : Rocket replaces Rocket -1 { 
	Default {
		
		Radius 9;
	}
	States
	{
	}
}

CLASS DH_PlasmaBall : PlasmaBall replaces PlasmaBall -1 { 
	Default {
		
		Radius 4;
		Height 4;
	}
	States
	{
	}
}

CLASS DH_TeleportFog : TeleportFog replaces TeleportFog -1 { 
	Default {
		
		+NOSECTOR;
		RenderStyle "Normal";
	}
	States
	{
	}
}

CLASS DH_TeleportDest : TeleportDest replaces TeleportDest 14 { 
	Default {
		
		Height 300;
		+SOLID;
		+SHOOTABLE;
		+SPAWNCEILING;
		+NOGRAVITY;
	}
	States
	{
	}
}

CLASS DH_GreenArmor : GreenArmor replaces GreenArmor 2018 { 
	Default {
		
	}
	States
	{
		Spawn:
			ARM1 A -1();
			stop;
	}
}

CLASS DH_BlueArmor : BlueArmor replaces BlueArmor 2019 { 
	Default {
		
		+NOSECTOR;
	}
	States
	{
	}
}

CLASS DH_Soulsphere : Soulsphere replaces Soulsphere 2013 { 
	Default {
		
	}
	States
	{
		Spawn:
			SOUL ABCDCB 6();
			goto Spawn;
	}
}

CLASS DH_InvulnerabilitySphere : InvulnerabilitySphere replaces InvulnerabilitySphere 2022 { 
	Default {
		
	}
	States
	{
		Spawn:
			PINV ABCD 6();
			goto Spawn;
	}
}

CLASS DH_Berserk : Berserk replaces Berserk 2023 { 
	Default {
		
	}
	States
	{
		Spawn:
			PSTR A -1();
			stop;
	}
}

CLASS DH_BlurSphere : BlurSphere replaces BlurSphere 2024 { 
	Default {
		
	}
	States
	{
		Spawn:
			PINS ABCD 6();
			goto Spawn;
	}
}

CLASS DH_RadSuit : RadSuit replaces RadSuit 2025 { 
	Default {
		
	}
	States
	{
		Spawn:
			SUIT A -1();
			stop;
	}
}

CLASS DH_Allmap : Allmap replaces Allmap 2026 { 
	Default {
		
	}
	States
	{
		Spawn:
			PMAP ABCDCB 6();
			goto Spawn;
	}
}

CLASS DH_BFG9000 : BFG9000 replaces BFG9000 2006 { 
	Default {
		
		Weapon.SlotNumber 7;
		Weapon.SlotPriority 1;
	}
	States
	{
		Deselect:
			SAWG D 10 A_Lower();
		State_67:
			SAWG CD 14 A_WeaponReady();
			BFGG A 14 A_Light2();
			SAWG D 14 A_Light1();
			goto State_67;
		Select:
			SAWG B 6 A_Raise();
			BFGG B 6 A_Saw();
			SAWG B 6 A_Saw();
			SAWG A 6 A_ReFire();
			goto Select;
		Ready:
			BFGG C 60 A_WeaponReady();
			goto Ready;
		Fire:
			BFGG C 0 A_BFGSound();
			BFGG C 60 A_WeaponReady();
			goto Ready;
		Flash:
			SAWG D 14 A_Light1();
		State_67:
			SAWG CD 14 A_WeaponReady();
			BFGG A 14 A_Light2();
			goto Flash;
	}
}

CLASS DH_Chainsaw : Chainsaw replaces Chainsaw 2005 { 
	Default {
		
		Weapon.SlotNumber 1;
		Weapon.SlotPriority 1;
	}
	States
	{
		Deselect:
			SAWG C 3 A_Lower();
			goto Deselect;
		Select:
			SAWG C 3 A_Raise();
			goto Select;
		Ready:
			SAWG CD 14 A_WeaponReady();
			BFGG A 14 A_Light2();
			SAWG D 14 A_Light1();
			goto Ready;
		Fire:
			BFGG B 6 A_Saw();
			SAWG B 6 A_Saw();
			SAWG A 6 A_ReFire();
			SAWG B 6 A_Raise();
			goto Fire;
	}
}

CLASS DH_ShortGreenColumn : ShortGreenColumn replaces ShortGreenColumn 31 { 
	Default {
		
		Health 60;
		Height 48;
		+SHOOTABLE;
		DeathSound "aleg/death";
	}
	States
	{
		Death:
			ALEG B 5();
			ALEG C 5 A_XScream();
			ALEG D 5 A_Fall();
			ALEG E -1();
			stop;
	}
}

CLASS DH_TallRedColumn : TallRedColumn replaces TallRedColumn 32 { 
	Default {
		
		Radius 8;
		Height 72;
	}
	States
	{
	}
}

CLASS DH_ShortRedColumn : ShortRedColumn replaces ShortRedColumn 33 { 
	Default {
		
		Radius 8;
		Height 72;
	}
	States
	{
	}
}

CLASS AliensTCLandingLights : EvilEye { 
	Default {
		Tag "Landing lights";
		Radius 7;
		Height 65;
	}
	States
	{
		Spawn:
			ALLT A 13 Bright;
			ALLT B 4 Bright;
			ALLT CD 13 Bright;
			loop;
	}
}

CLASS AliensTCFacehuggerEggUnhatched : FloatingSkull { 
	Default {
		Tag "Facehugger Egg, unhatched";
		Health 60;
		Height 40;
		Mass 300;
		+SHOOTABLE;
		DeathSound "aleg/death";
	}
	States
	{
		Spawn:
			ALEG A -1();
			stop;
		Death:
			ALEG B 5();
			ALEG C 5 A_XScream();
			ALEG D 5 A_Fall();
			ALEG E -1();
			stop;
	}
}

CLASS AliensTCBigRock2 : TorchTree { 
	Default {
		Tag "Big Rock 2";
		Radius 155;
		Height 120;
		+DONTTHRUST;
	}
	States
	{
		  Spawn:
			ALBR B -1();
			stop:
	}
	}
}

CLASS AliensTCLadder : BlueTorch { 
	Default {
		Tag "Ladder (192 high)";
		Radius 12;
		Height 192;
	}
	States
	{
		Spawn:
			ALLD A -1 A_Look();
			loop;
	}
}

CLASS AliensTCHangingLightDead : GreenTorch replaces GreenTorch 45 { 
	Default {
		Tag "Hanging light (dead)";
		Radius 24;
		Height 32;
		-SOLID;
		+SPAWNCEILING;
		+NOGRAVITY;
	}
	States
	{
		Spawn:
			ALHL B -1();
			stop;
	}
}

CLASS AliensTCHangingLightLit : RedTorch { 
	Default {
		Tag "Hanging light (Lit)";
		Radius 24;
		Height 32;
		-SOLID;
		+SPAWNCEILING;
		+NOGRAVITY;
	}
	States
	{
		Spawn:
			ALHL A -1 Bright;
			stop;
	}
}

CLASS AliensTCLargeFlames : ShortBlueTorch { 
	Default {
		Tag "Large flames"
		Radius 76;
		Height 104;
		-SOLID;
	}
	States
	{
		Spawn:
			ALLF ABCD 4 Bright;
			goto Spawn;
	}
}

CLASS AliensTCSmallFlameOnSlimePile : ShortGreenTorch { 
	Default {
		Tag "Small flame on slime pile"
		Health 1;
		Radius 6;
		Height 76;
		+DONTTHRUST;
		-SOLID;
		+SHOOTABLE;
		+NOBLOOD;
	}
	States
	{
		Spawn:
			ALIN A -1 Bright;
			stop;
		Death:
			ALSF EFGH 4 Bright;
			goto Death;
		XDeath:
			ALSF EFGH 4 Bright;
			goto Death;
	}
}

CLASS AliensTCSmallFlame : ShortRedTorch { 
	Default {
		Tag "Small flame on ground";
		Radius 10;
		-SOLID;
	}
	States
	{
		Spawn:
			ALSF ABCD 4 Bright;
			loop;
	}
}

CLASS AliensTCBigRock3 : Candelabra { 
	Default {
		Tag "Big Rock 3";
		Radius 165;
		Height 154;
		+DONTTHRUST;
	}
	States
	{
		Spawn:
			ALBR C -1();
			stop;
	}
}


CLASS AliensTCDrippingWater : NonsolidTwitch { 
	Default {
		Tag "Dripping Water (104 high)";
		Height 104;
		+SPAWNCEILING;
		+NOGRAVITY;
	}
	States
	{
		Spawn:
			ALDW ABC 5();
			ALDW D 5();
			ALDE E 5();
			loop;
	}
}

CLASS AliensTCComplexPipes : DeadDoomImp { 
	Default {
		Tag "Complex pipes (104 high)";
		Radius 32;
		Height 104;
		+SOLID;
	}
	States
	{
		Spawn:
			ALCP A -1();
			stop;
	}
}

CLASS AliensTCHoleInCeiling : HeadsOnAStick { 
	Default {
		Tag "Hole in ceiling";
		Radius 12;
		Height 30;
		-SOLID;
		+SPAWNCEILING;
		+NOGRAVITY;
	}
	States
	{
	Spawn:
		ALHO A -1();
		stop;
	}
}

CLASS AliensTCTwinPipes : HeadOnAStick { 
	Default {
		Tag "Twin pipes (104 high)";
		Height 104;
		+DONTTHRUST;
	}
	States
	{
		Spawn:
			ALTP A -1();
    		stop;
	}
}


CLASS AliensTCDestroyableSlimeColumn : BigTree { 
	Default {
		Tag "Destroyable slime column";
		Health 150;
		Radius 16;
		Height 76;
		+DONTTHRUST;
		+SHOOTABLE;
		+NOBLOOD;
	}
	States
	{
		Death:
			ALSC A 5();
			ALSC B 5 A_Scream();
			ALSC CD 5();
			ALSC E 5 A_Fall();
			ALSC F 5();
			ALSC G -1();
			stop;
	}
}

